name = "dialoguemaker/kit"
version = "0.1.0"
description = "A collection of tools and utilities for building dialogue systems in Roblox, including examples, themes, effects, and other packages."
authors = ["Christian Toney <christian.toney@beastslash.com>"]
repository = "https://github.com/DialogueMaker/kit"
license = "GPL-3.0"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**/*.lua",
]
private = true

[target]
environment = "roblox"
lib = "src/init.client.lua"
build_files = ["src"]

[engines]
pesde = "^0.7.0-rc.4"
lune = "^0.8.9"

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.47.0", target = "lune" }

[dependencies]
react = { wally = "jsdotlua/react", version = "^17.2.1" }
react-roblox = { wally = "jsdotlua/react-roblox", version = "^17.2.1" }
Dialogue = { name = "dialoguemaker/dialogue", version = "^0.1.10" }
Client = { name = "dialoguemaker/client", version = "^0.1.6" }
Conversation = { name = "dialoguemaker/conversation", version = "^0.1.10" }
DialogueMakerTypes = { name = "dialoguemaker/types", version = "^0.1.27" }
Message = { name = "dialoguemaker/message", version = "^0.1.6" }
Response = { name = "dialoguemaker/response", version = "^0.1.5" }
Redirect = { name = "dialoguemaker/redirect", version = "^0.1.6" }
StandardTheme = { name = "dialoguemaker/standard_theme", version = "^0.1.5" }
PauseEffect = { name = "dialoguemaker/pause_effect", version = "^0.1.0" }
